apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flipkart
  template:
    metadata:
      labels:
        app: flipkart
    spec:
      containers:
      - name: flipkart-image
        image: acrfortesting098.azurecr.io/flipkartapp:latest
        ports:
        - containerPort: 8080
