apiVersion: v1
kind: Service
metadata:
  name: flipkart-service
  labels:
    app: flipkart
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: flipkart